[platformio]
default_envs = app

[env:app]
platform = https://github.com/maxgerhardt/platform-nordicnrf52
board = xiaoblesense_adafruit
framework = arduino
board_build.ldscript = linker/nrf52840_s140_v7_app.ld
;board_build.offset = 0x020000  ; 0x27000 dispatcher + 0x8000 offset = 0x2F000
build_flags =
    ;-DNRFX_NVMC_ENABLED=1
    ;-DNRFX_NVMC_CONFIG_LOG_ENABLED=0
    ;-DNRFX_NVMC_CONFIG_INFO_COLOR=0
;    -DAPP_ADDR=0x2F000
;    -DUPDATER_ADDR=0x8F000
;    -DDISPATCHER_ADDR=0x27000
;    -DBOOTFLAG_ADDR=0xEF000
;    -DBOOT_SLOT_APP=0xAABBCCDD
;    -DBOOT_SLOT_UPDATER=0x11223344
build_src_filter = +<app>
lib_archive = no
extra_scripts = post:tools/auto_build_merge.py

[env:updater]
platform = https://github.com/maxgerhardt/platform-nordicnrf52
board = xiaoblesense_adafruit
framework = arduino
board_build.ldscript = linker/nrf52840_s140_v7_updater.ld
build_flags =
    ;-DNRFX_NVMC_ENABLED=1
    ;-DNRFX_NVMC_CONFIG_LOG_ENABLED=0
    ;-DNRFX_NVMC_CONFIG_INFO_COLOR=0
build_src_filter = +<updater>
lib_archive = no

