[platformio]
default_envs = app

[env:common]
platform = https://github.com/maxgerhardt/platform-nordicnrf52
board = xiaoblesense_adafruit
framework = arduino
monitor_speed = 115200
lib_archive = no

[env:app]
extends = env:common
board_build.ldscript = linker/nrf52840_s140_v7_app.ld
build_src_filter = +<app>
extra_scripts =
    post:tools/auto_build.py
upload_port = COM29

[env:updater]
extends = env:common
board_build.ldscript = linker/nrf52840_s140_v7_updater.ld
build_src_filter = +<updater>


